enableImmutableInstalls: false

enableInlineBuilds: false

enableTelemetry: false

httpTimeout: 60000

logFilters:
  - code: YN0006
    level: discard
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: ./jupyterlab/staging/yarn.js
