name: Build Wheels All Platforms

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11.8']
        include:
          - os: ubuntu-latest
            arch: x64

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,test]"
          pip install hatchling

      - name: Install and build JavaScript dependencies
        run: |
          jlpm run prebuild:all
          jlpm install
          jlpm run build

      - name: Build wheel
        run: |
          npm run prepare:python-release:no-git

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*.whl
