name: Build Wheels All Platforms

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        python-version: ['3.11']
        include:
          - os: ubuntu-latest
            arch: x86_64
          # - os: ubuntu-latest
          #   arch: i686
          # - os: windows-latest
          #   arch: x86
          # - os: windows-latest
          #   arch: x64
          # - os: macos-latest
          #   arch: x86_64
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,test]"
          pip install hatchling

      - name: Install and build JavaScript dependencies
        run: |
          jlpm run prebuild:all
          jlpm install
          jlpm run build

      - name: Build wheel
        run: |
          npm run prepare:python-release:no-git

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./dist/*.whl
