name: Build Wheels All Platforms

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.8']
        include:
          - os: windows-latest
            platform: win_amd64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman

      - name: Install dependencies
        run: |
          pip install -e ".[dev,test]"

      - name: JavaScript dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          npm install -g yarn
          New-Alias -Name jlpm -Value yarn

      - name: Install and build JavaScript dependencies
        run: |
          jlpm run prebuild:all
          jlpm install
          jlpm run build

      - name: Prepare Python release
        run: |
          npm run prepare:python-release:github-actions

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - name: Upload built wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}

  combine_wheels:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./combined_wheels

      - name: Display structure of downloaded files
        run: ls -R ./combined_wheels

      - uses: actions/upload-artifact@v3
        with:
          name: all-wheels
          path: ./combined_wheels/**/*.whl