name: Build Wheels All Platforms

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.11.x']
        arch: [x64]
        include:
          - os: windows-latest
            platform: win32

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman

      - name: Install dependencies
        run: |
          pip install -e ".[dev,test]"

      - name: Install and build JavaScript dependencies
        run: |
          jlpm run prebuild:all
          jlpm install
          jlpm run build

      - name: Build platform-specific wheels
        run: |
          npm run prepare:python-release:github-actions

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*.whl

  combine_wheels:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: ./dist

      - name: Display structure of downloaded files
        run: ls -R ./dist

      - uses: actions/upload-artifact@v3
        with:
          name: combined-wheels
          path: ./dist/*.whl
