# https://github.com/marketplace/actions/labeler
name: "Pull Request Labeler"
on:
- pull_request_target

permissions:
  pull-requests: write

jobs:
  triage:
    name: Update PR Labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
